// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow to analyze a website and suggest relevant keywords for SEO.
 *
 * - analyzeWebsiteKeywords - A function that analyzes a website and suggests keywords.
 * - AnalyzeWebsiteKeywordsInput - The input type for the analyzeWebsiteKeywords function.
 * - AnalyzeWebsiteKeywordsOutput - The return type for the analyzeWebsiteKeywords function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeWebsiteKeywordsInputSchema = z.object({
  websiteUrl: z
    .string()
    .url()
    .describe('The URL of the website to analyze.'),
});
export type AnalyzeWebsiteKeywordsInput = z.infer<
  typeof AnalyzeWebsiteKeywordsInputSchema
>;

const AnalyzeWebsiteKeywordsOutputSchema = z.object({
  keywords: z
    .array(z.string())
    .describe('An array of relevant keywords for the website.'),
  explanation: z
    .string()
    .describe('Explanation of why the keywords are relevant.'),
});
export type AnalyzeWebsiteKeywordsOutput = z.infer<
  typeof AnalyzeWebsiteKeywordsOutputSchema
>;

export async function analyzeWebsiteKeywords(
  input: AnalyzeWebsiteKeywordsInput
): Promise<AnalyzeWebsiteKeywordsOutput> {
  return analyzeWebsiteKeywordsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeWebsiteKeywordsPrompt',
  input: {schema: AnalyzeWebsiteKeywordsInputSchema},
  output: {schema: AnalyzeWebsiteKeywordsOutputSchema},
  prompt: `You are an SEO expert. Analyze the website at the following URL and suggest relevant keywords to improve its search engine ranking.

URL: {{{websiteUrl}}}

Return a JSON object with a 'keywords' field containing an array of keywords and an 'explanation' field explaining why the keywords are relevant.
`,
});

const analyzeWebsiteKeywordsFlow = ai.defineFlow(
  {
    name: 'analyzeWebsiteKeywordsFlow',
    inputSchema: AnalyzeWebsiteKeywordsInputSchema,
    outputSchema: AnalyzeWebsiteKeywordsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
